///***USERS QUERY***///
//GET http://localhost:5000/api/user
//GET http://localhost:5000/api/user/1

# POST http://localhost:5000/api/user
# Content-Type: application/json

# {
#     "User_FirstName": "Natali",
#     "User_LastName": "Enot",
#     "User_PhotoPath": "/test.jpg",
#     "User_Email": "test@gmail.com",
#     "User_Password": "natashanatasha",
# }

# PUT http://localhost:5000/api/user/2
# Content-Type: application/json

# {
#     "User_FirstName": "Tom",
#     "User_LastName": "Kekichex",
#     "User_PhotoPath": "/test.jpg",
#     "User_Email": "tom@gmail.com",
#     "User_Password": "tomtom",
# }

//DELETE http://localhost:5000/api/user/16

///***TASKS***///
//GET http://localhost:5000/api/task/getAll
//Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Ik5hdGFsaSIsIm5iZiI6MTU5MjUwNzE3MSwiZXhwIjoxNTkyNTA4OTcxLCJpYXQiOjE1OTI1MDcxNzF9.vaHrYw8ue6MVJA8SXWWb2KMc2b63riEDIOdzuXNfTv0

//DELETE http://localhost:5000/api/task/deleteTask/40

//GET http://localhost:5000/api/task/getOne/1
GET http://localhost:5000/api/task/userTasks/1/2/0
//Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Ik5hdGFsaSIsIm5iZiI6MTU5MjUxMjIzNywiZXhwIjoxNTkyNTE0MDM3LCJpYXQiOjE1OTI1MTIyMzd9._AZRoGpi_-LwDUt-gEaQojfNgVMjo6zaYdrstTdf2W4


# POST http://localhost:5000/api/task/addTask
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Ik5hdGFsaSIsIm5iZiI6MTU5MjUwNzE3MSwiZXhwIjoxNTkyNTA4OTcxLCJpYXQiOjE1OTI1MDcxNzF9.vaHrYw8ue6MVJA8SXWWb2KMc2b63riEDIOdzuXNfTv0
# Content-Type: application/json

# {
#     "Task_Priority": "green",
#     "Task_Name": "English",
#     "Task_Description": "learn all tenses",
#     "UserId": 1,
#     "IsArchived": "false",
# }

# PUT http://localhost:5000/api/task/updateTask/4
# Content-Type: application/json

# {
#      "Task_Priority": "gray",
#      "Task_Name": "newChanged3",
#      "Task_Description": "newChanged",
#      "UserId": "2",
#      "IsArchived": "true",
# }

//POST https://localhost:5001/api/authenticate/auth
# Content-Type: application/json

# {
#     "User_Email": "test@gmail.com",
#     "User_Password": "natashanatasha"
# }

